parameters:
    ez_react_styled:
        rails_components_dir: '/components'
        webpack_config_dir: '/configs'
        server_bundle_dir: '/server'
        server_bundle_name: 'server-bundle'
        entry_point_name: 'ez_react_styled'

services:

    Gie\EzReactStyledBundle\Command\GenerateWebpackFilesCommand:
        autowire: true
        arguments:
            $config: "%ez_react_styled%"
            $projectDir: '%kernel.project_dir%'
        tags:
            -  { name: console.command }

    Gie\EzReactStyledBundle\Twig\ReactStyledExtension:
        parent: 'limenius_react.render_extension'
        calls:
            - [setTagRenderer, ['@webpack_encore.tag_renderer']]
            - [setConfig, ['%ez_react_styled%']]
        tags:
            - { name: twig.extension }
